module.exports = {
    words: {
        minor: [
            "milf",
            "dilf",
            "kkk",
            "dtf",
            "std",
            "chlamydia",
            "gonorrhea",
            "herpe",
            "crab disease",
            "acab",
            "all cops are bastards",
            "hitler",
            "nazi",
            "stalin",
            "zedong",
            "gulag",
            "concentration camp",
            "gas chamber",
            "death chamber",
            "kapo",
            "mengele",
            "swastika",
            "suicide",
            "aids",
            "abortion",
            "stripper",
            "autistic",
            "midget",
            "fetish",
            "prick"
        ],
        major: [
            "nigga",
            "nigger",
            "niggie",
            "chink",
            "honkey",
            "shemale",
            "tranny",
            "beaner",
            "kurac",
            "kys",
            "killyourself",
            "kill yourself",
            "niger",
            "faggot",
            "fag",
            "dyke",
            "incest",
            "masturbate",
            "jack off",
            "wank",
            "pedo",
            "paedo",
            "perv",
            "rape",
            "rapist",
            "whore",
            "slut",
            "thot",
        ]
    },
    websiteWhitelist: [
        "https://phantomhq.club/",
        "https://cdn.discord.com",
        "https://tinypic.com",
        "https://twitch.tv",
        "https://prntr.com",
        "https://gfycat.com",
        "https://twitter.com",
        "https://youtube.com",
        "https://youtu.be",
        "https://prnt.sc",
        "https://gyazo.com",
        "https://imgur.com"
    ]
};